// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-z1MD-fKqEyaRcqw9PZGdBwicJhcqhlg',
    appId: '1:252456924958:web:533becae5e1b29c077fb0f',
    messagingSenderId: '252456924958',
    projectId: 'quizzy-6ec7b',
    authDomain: 'quizzy-6ec7b.firebaseapp.com',
    storageBucket: 'quizzy-6ec7b.firebasestorage.app',
    measurementId: 'G-R9BTZ5FY5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKdsZ6QHQO9RBGoIVep-suOynMNMTJWRQ',
    appId: '1:252456924958:android:8bc43344c2177cae77fb0f',
    messagingSenderId: '252456924958',
    projectId: 'quizzy-6ec7b',
    storageBucket: 'quizzy-6ec7b.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkHvAodKl4IyR1Bqh1-Vg1M61VY3Mjr94',
    appId: '1:252456924958:ios:776f03d13a98607377fb0f',
    messagingSenderId: '252456924958',
    projectId: 'quizzy-6ec7b',
    storageBucket: 'quizzy-6ec7b.firebasestorage.app',
    iosBundleId: 'com.example.quizz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-z1MD-fKqEyaRcqw9PZGdBwicJhcqhlg',
    appId: '1:252456924958:web:32076ac30cd6699177fb0f',
    messagingSenderId: '252456924958',
    projectId: 'quizzy-6ec7b',
    authDomain: 'quizzy-6ec7b.firebaseapp.com',
    storageBucket: 'quizzy-6ec7b.firebasestorage.app',
    measurementId: 'G-Z1Y8G23N2B',
  );
}
